version: "3.8"
services:
  next-app:
    build:
      context: ./portfolio-website
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3020:80"
    restart: always
    depends_on:
      - next-app
