name: Production-Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  react-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Soruce Code
        uses: actions/checkout@v4
      - name: Login to Gocker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t muhammadhaziq/portfolio .
      - name: Run Lint
        run: docker run -e CI=true muhammadhaziq/portfolio npm run lint
  build:
    runs-on: ubuntu-latest
    needs: react-lint
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t muhammadhaziq/portfolio .
      - name: Push Docker Image
        run: docker push muhammadhaziq/portfolio

  # deploy:
  #   if: github.event_name == 'push'
  #   needs: react-lint # Ensure build completes before deploying
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  #     - run: docker build -t muhammadhaziq/portfolio:latest .
  #     - run: docker run -e CI=true muhammadhaziq/portfolio:latest npm run lint

  #     - name: Generate deployment package
  #       run: zip -r deploy.zip . -x '*.git*' -x 'node_modules/*' -x 'docker-compose.yml'

  #     - name: Deploy to EB
  #       uses: einaregilsson/beanstalk-deploy@v18
  #       with:
  #         application_name: ${{ secrets.EB_APP_NAME }}
  #         environment_name: ${{ secrets.EB_ENV_NAME }}
  #         existing_bucket_name: elasticbeanstalk-us-east-2-153776375821
  #         region: ${{ secrets.AWS_REGION }}
  #         version_label: ${{ github.sha }}
  #         deployment_package: deploy.zip
  #         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
